### ISSUE TITLE
デバッグログが残っている

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#26]
@yamamoto-shunsuke 
console.log()がまだ残っているようなので、削除をお願いします。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちらの修正はhotfix/debuglog_deleteブランチにて行います。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
修正いたしましたので、ご確認の程よろしくお願いいたします。
https://github.com/school-pj/profile/pull/61
