### ISSUE TITLE
var宣言が残っている

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#27]
@yamamoto-shunsuke 
routesフォルダ以下のjsファイルについて、変数の宣言にvarを使っている箇所が多々あります。
宣言後、代入が行われるのであればletで、行われないのであればconstで宣言をするよう修正してください。

1ファイルごとでなく1つのブランチで一気に修正してしまって大丈夫です。
最新のmainからブランチを作成して修正をお願いします！

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちらの修正はhotfix/debuglog_deleteブランチで修正済みです。
https://github.com/school-pj/profile/pull/61
