### ISSUE TITLE
【バグ】サインイン時、ユーザ名が間違っているとエラー

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#28]
@yamamoto-shunsuke 
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'password' of undefined

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちらは、昨日マージしたハッシュ化のブランチにて既にに修正済みです。

**Comment by Ivakov** [comment]
修正を確認済みなのでクローズします。
