### ISSUE TITLE
【バグ】トップページのフォロー数がおかしいときがある

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#30]
@yamamoto-shunsuke 
調査、修正をお願いします。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
hotfix/follow_number_bagブランチにて、修正を行います。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
お疲れ様です。山本です。
フォロー数がおかしい時がある件について、ご相談がございます。
トップページ⇒ユーザー一覧ページ⇒プロフィールページにてフォロー
上記順番で進めていった際に、フォローボタンを押した後、トップページまでブラウザバックした際に、フォローの処理が反映されていないことを確認いたしました。
疑問があるのですが、ブラウザバックすることで、処理が反映されていないことは正常ではないでしょうか。ブラウザバックとは更新を行うものではないので、戻った際に、フォロー処理が反映されているほうがおかしいような気もします。
一応、metaタグで自動でリロードするコードを記述することによって、フォローした処理がブラウザバックしても反映されていることをすぐ確認することもできますが、これ以外の方法を調べたところ、解決につながるようなサイト等見つけることができませんでした。
岩舘さんの方で何かほかに解決できる方法など知っていましたら、ヒントとしてご教授いただきたいです。

**Comment by Ivakov** [comment]
@yamamoto-shunsuke 
コンソールをみながら動作確認すると分かりやすいと思いますが、
ブラウザバックではリクエストは走らないので、トップページまでブラウザバックした際に数が反映されていないのは正しいです。
(トップページまでブラウザバックし、ページリロードするとリクエストが走るので反映されます)

ここは特に対応する必要はないので、リクエストが走っているのに反映されない等の致命的な問題がなければ大丈夫です

**Comment by Ivakov** [comment]
@yamamoto-shunsuke 
もしかすると、ブラウザバックした際に数が反映されていないことを、リクエストが走っているのに反映されないと勘違いしてissue化してしまった可能性があるので、リクエストが走れば正しく反映されることが確認できたらこのisuueを閉じようと思います。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
ご確認ありがとうございます。
リクエストが走れば、正しく反映されますので。issueのcloseをお願いいたします。

**Comment by Ivakov** [comment]
@yamamoto-shunsuke
念のためこちらでも一通り確認してからクローズします。
