### ISSUE TITLE
日本語表記と英語表記が混ざっている

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#31]
ボタン名、タイトル等、日本語表記と英語表記が混ざっているので、英語表記に統一するようお願いします。
頭文字は基本大文字で。
また、タイトルはh1、ユーザ名はh2で統一してください。

- ログインページ
  - ボタン名
    - 「ログイン」->「Login」

  - タイトル
    - 「ログイン」->「Login」

- サインアップページ
  - ボタン名
    - 「登録」->「Sign up」

  - タイトル
    - 「新規会員登録」->「Sign up」

- トップページ(ログイン後)
  - ボタン名
    - 「投稿」->「Post」

  - その他
    - 「自己紹介文」->「Introduction」
    - 「フォロー」->「Follows」
    - 「フォロワー」->「Followers」

- プロフィールページ
  - その他
    - 「フォロー」->「Follows」
    - 「フォロワー」->「Followers」

- 設定ページ
  - タイトル
    - 「アカウント設定」->「Settings」

  - ボタン名
    - 「OK」->「Update」

  - その他
    - 「新しいユーザー名 」->「New Username」
    - 「新しいパスワード」->「New Password」
    - 「確認のためパスワードを再入力」->「New Password (retype)」

**Comment by Ivakov** [comment]
@h-ikeshita 
こちら池下さんの方で対応をお願いします！

ローカルのmainブランチをpullして最新にして、そこからブランチを作成し、修正完了したらpushとプルリク作成をお願いします！

**Comment by yamamoto-shunsuke** [comment]
@h-ikeshita 
ログイン時、パスワードが誤っていた際に、表示されるフラッシュメッセージが日本語表記のままになっておりますが、こちらは既に修正されましたでしょうか。
ご確認のほどよろしくお願いいたします。m(__)m

**Comment by h-ikeshita** [comment]
@yamamoto-shunsuke hotfix/language_enブランチの初回コミットでは未対応でしたがその後のコミットで対応しました。
以下のコミットです。

フラッシュメッセージを英語に変更_TODO:index.jsのcontent表示箇所がNullを起こしている
1d4d582

login.jsファイル

以上、ご確認よろしくお願いいたします。

**Comment by yamamoto-shunsuke** [comment]
@h-ikeshita 
ご返信ありがとうございます。
承知いたしました！
