### ISSUE TITLE
トップページとプロフィールページのtextareaの枠を固定にする

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#32]
現在は可変なので、良き大きさに固定する。
トップページのもの (2つ)もプロフィールページのものも大きさは揃える。

**Comment by Ivakov** [comment]
@h-ikeshita 
こちら池下さんの方で対応をお願いします！

ローカルのmainブランチをpullして最新にして、そこからブランチを作成し、修正完了したらpushとプルリク作成をお願いします！

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちら私の方で対応いたします。
hotfix/top_profile_textareaブランチで行います。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちらの修正はfeature/top_textarea_positionブランチで修正を行います。
