### ISSUE TITLE
池下さん担当ページのbootstrap適用

### ISSUE THREAD

**Issue by yamamoto-shunsuke** [school-pj/profile#41]

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちらの修正は、hotfix/bootstrap_pageブランチで行います。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
共有です。
フォロワーページにおいて、点ごとリンクで表示されていたため、その問題もこちらのブランチで修正いたします。
また、トップページやプロフィールページ等のことですが、ユーザー名はh2タグ、follow、followerなどの文字の大きさはh3タグなど、一部テキストの大きさの修正もこちらで行ってしまおうかと思います。

**Comment by Ivakov** [comment]
@yamamoto-shunsuke 
了解です！

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちらのissueはhotfix/boostrap_pageブランチを修正いたしました。
