### ISSUE TITLE
Follows、Followers数が見づらい

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#44]
@yamamoto-shunsuke 
現状、以下のように項目と数の間に間隔がないため見づらいです。
Follows5
Followers8

間隔を開けるよう修正をお願いします。
修正は https://github.com/school-pj/profile/pull/38 でお願いします。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
hotfix/follow_follower_Layoutブランチを作成して、そちらで修正を行います。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
フォローフォロワー数表示位置の変更修正完了しました。
