### ISSUE TITLE
ログイン状態の判断にreq.isAuthenticated()を使う

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#55]

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちらの修正はhotfix/login_authenticateブランチにて行います。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
修正いたしましたので、ご確認の程よろしくお願いいたします。
https://github.com/school-pj/profile/pull/59
