### ISSUE TITLE
ルーティングをapp.jsではなくroutes内で行う

### ISSUE THREAD

**Issue by Ivakov** [school-pj/profile#57]

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
こちらの修正をhotfix/routing_pageブランチで行います。

**Comment by yamamoto-shunsuke** [comment]
app.use('routes',require('./routes')); ←app.jsに記述(routesフォルダの読み込み)

router.use('/', require('./index')); ←index.jsに記述(各ページのルーティング読み込み)
↓上記のようにそれぞれのページのルーティング記述。

上記のような形でroutesフォルダから各ページのルーティング処理を記述したのですが、ルーティングが正常に行われず、エラーになってしまいます。
エラー文：Router.use() requires a middleware function but got a Object

app.jsでは、routesフォルダの読み込みは実装できているみたいですが、それ以降の各ページのルーティングの読み込みができておりません。

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
修正完了いたしましたので、ご確認の程よろしくお願いいたします。
https://github.com/school-pj/profile/pull/65

**Comment by yamamoto-shunsuke** [comment]
@Ivakov 
ルーティングをapp.jsではなくroutes内で行い、無事にページ遷移することができ、パスポート機能に関しましても、モデル化し、機能が正常に動作していることが確認でき(モデル化したuser.jsも同様)、ログアウト機能に関しましても正常に動作いたしました。そのため、こちらのに関しましては、修正完了いたしましたので、closeお願いいたします。
